export default {
  id: 17,
  name: "Chicken Wire",
  type: "Agar",
  source: "https://www.conwaylife.com/patterns/chickenwire.cells",
  config: [[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,],
[true,true,false,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,true,true,true,false,false,false,false,true,true,],
[false,false,true,true,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,false,false,false,true,true,false,false,false,true,true,true,true,] ]
};
