export default {
  id: 843,
  name: "Dart",
  type: "Space Ship",
  source: "https://www.conwaylife.com/wiki/Dart",
  config: [
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [false, false, false, false, false, false, true, false, true],
    [false, false, false, false, false, true, false, false, false, true],
    [false, false, false, false, false, false, true, true, true],
    [],
    [false, false, false, false, true, true, false, false, false, true, true],
    [
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true
    ],
    [
      false,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      true
    ],
    [
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      true
    ],
    [
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      true,
      false,
      true
    ]
  ]
};
