export default {
  name: "Canada Goose",
  order: 51,
  type: "spaceship",
  source: "https://www.conwaylife.com/wiki/Canada_goose",
  config: [
    [true, true, true],
    [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true
    ],
    [
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      true
    ],
    [false, false, false, true, true, false, false, true, true],
    [false, false, false, false, true],
    [false, false, false, false, false, false, false, false, true],
    [false, false, false, false, true, true, false, false, false, true],
    [false, false, false, true, false, true, false, true, true],
    [
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      true
    ],
    [false, false, true, false, false, false, false, true, true],
    [false, false, true, true],
    [false, false, true, true]
  ]
};
