export default {
  name: "Crab",
  order: 42,
  type: "spaceship",
  source: "https://www.conwaylife.com/wiki/Crab",
  config: [
    [false, false, false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, false, false, false, true],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true
    ],
    [],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      true
    ],
    [false, true, true, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, true],
    [false, false, true, false, false, false, false, true, false, true],
    [false, false, false, false, true, true, false, false, true],
    [false, false, false, false, true, true]
  ]
};
